sudo: required
services:
  - docker

before_install:
  - docker build -t ashil/docker-react -f Dockerfile.dev .

script:
  - docker run ashil/docker-react npm run test -- --coverage

  deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-025474164248"
    bucket_path: "docker-react"
    on:
      branch: master
